# See also: https://github.com/tmux/tmux/wiki/Getting-Started

set-option -g default-shell /bin/zsh
set-option -sg escape-time 10
# set -as terminal-features ',rxvt-unicode-256color:clipboard'
# set -g default-terminal "xterm-256color"
set -g default-terminal "screen-256color"
set-option -sa terminal-features ',screen-256color:RGB'

# Enable copy-mode-vi
setw -g mode-keys vi
bind-key -n F4 copy-mode # Start copy-mode with F4 (TODO: consider another keybinding)

# Setup more vim-like keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R
# Setup other keybindings
bind-key -n M-t select-pane -U # Requires disabling this binding is VS Code, though...
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Setup aliases
set -s 'command-alias[100]' 'vsp=split-window -h'
set -s 'command-alias[101]' 'tsw=split-window -h tsc -w'
set -s 'command-alias[102]' 'exit=kill-session'
set -s 'command-alias[103]' 'tu=resize-pane -U'
set -s 'command-alias[104]' 'td=resize-pane -D'

# TO TEST FORMATS: tmux display -pv '#{==:#{CODESPACES},true}'

# Setup clipboard mode
%if #{==:#{CODESPACES},true}
    # Create a "fake clipboard", this will allow copying internally in codespaces running in the web using VIM copy mode
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'tee /tmp/clipboard_plus.txt'
%elif #{==:#{xclip_working},true}
    # Copy to xclip for sharing with system clipboard
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
&else
    display-message "XClip not working"
%endif
