set-option -g default-shell /bin/zsh
set-option -sg escape-time 10
# set -as terminal-features ',rxvt-unicode-256color:clipboard'
set -g default-terminal "xterm-256color"

# Enable copy-mode-vi
setw -g mode-keys vi
bind-key -n F4 copy-mode # Start copy-mode with F4 (TODO: consider another keybinding)

# Setup more vim-like keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key k select-pane -U
bind-key j select-pane -D
bind-key -n M-t select-pane -l # Requires disabling this binding is VS Code, though...
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# TO TEST FORMATS: tmux display -pv '#{==:#{CODESPACES},true}'
%if #{==:#{CODESPACES},true}
    # Create a "fake clipboard", this will allow copying internally in codespaces running in the web using VIM copy mode
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'tee /tmp/clipboard_plus.txt'
%else
    # Copy to xclip for sharing with system clipboard
    bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
%endif
