// GENERATED by the agent-harness linker from scripts/managed/fallback-matcher.mts — edit that, not this.
// agent-harness fallback guard
// @ts-nocheck

/**
 * The guard `.claude/fallback/guard.sh` runs when the bundle is absent: it asks before every
 * command the policy allows only within limits, and before a redirect that may write a file.
 * The linker renders it into each consumer's `.claude/fallback/matcher.mts` with the list filled in.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

// Splits a bash command string into words, operators, redirects, heredoc
// bodies and comments, honouring bash's quoting and expanding nothing.
// Imports nothing, so a generator can inline it where only Node built-ins load.
// `shell-lexer.oracle.test.ts` checks it against shfmt and real bash.

export type ShellExpansion = "parameter" | "command" | "arithmetic" | "process";

export type ShellControlOperator =
  | "&&"
  | "||"
  | ";;&"
  | ";;"
  | ";&"
  | "|&"
  | "|"
  | "&"
  | ";"
  | "("
  | ")"
  | "\n";

export type ShellRedirectOperator =
  | "&>>"
  | "<<<"
  | "<<-"
  | "&>"
  | "<<"
  | "<>"
  | "<&"
  | ">>"
  | ">&"
  | ">|"
  | "<"
  | ">";

interface ShellSpan {
  start: number;
  end: number;
}

export interface ShellWord extends ShellSpan {
  kind: "word";
  /** Quoting removed and `$'…'` decoded; every expansion kept as written. */
  text: string;
  /** Any quote or backslash escape outside an expansion. */
  quoted: boolean;
  /** Kinds found at this word's level, not inside a command substitution. */
  expansions: ShellExpansion[];
  /** Names of the parameters expanded at this word's level: `?` for `$?` or `${#?}`. */
  parameters: string[];
  /** Tokens of each `$(…)`, `<(…)` or backtick command in this word. */
  substitutions: ShellToken[][];
  /** An unquoted `{a,b}` or `{a..b}`, which bash splits into several words. */
  braceExpansion: boolean;
  /** An unquoted `*`, `?` or `[…]`, which bash replaces with matching paths. */
  pathnameExpansion: boolean;
}

export interface ShellOperator extends ShellSpan {
  kind: "operator";
  op: ShellControlOperator;
}

export interface ShellRedirect extends ShellSpan {
  kind: "redirect";
  op: ShellRedirectOperator;
  /** `2` in `2>&1`, `{fd}` in `{fd}>x`; the target is the next word token. */
  fd: string | null;
}

export interface ShellHeredoc extends ShellSpan {
  kind: "heredoc";
  /** Raw body, up to the delimiter line; the span also covers that line. */
  body: string;
  /** Empty when the delimiter was quoted, since bash then expands nothing. */
  expansions: ShellExpansion[];
  parameters: string[];
  substitutions: ShellToken[][];
}

export interface ShellComment extends ShellSpan {
  kind: "comment";
  /** Everything after the `#`, up to the end of the line. */
  text: string;
}

export type ShellToken =
  | ShellWord
  | ShellOperator
  | ShellRedirect
  | ShellHeredoc
  | ShellComment;

// Longest first, so `;;&` is not read as `;;` then `&`.
const CONTROL_OPERATORS: readonly ShellControlOperator[] = [
  ";;&",
  "&&",
  "||",
  ";;",
  ";&",
  "|&",
  "|",
  "&",
  ";",
  "(",
  ")",
];

const REDIRECT_OPERATORS: readonly ShellRedirectOperator[] = [
  "&>>",
  "<<<",
  "<<-",
  "&>",
  "<<",
  "<>",
  "<&",
  ">>",
  ">&",
  ">|",
  "<",
  ">",
];

const UNQUOTED_WORD_BREAKS = new Set([
  " ",
  "\t",
  "\n",
  "|",
  "&",
  ";",
  "(",
  ")",
  "<",
  ">",
]);

const REDIRECT_FD_PREFIX = /^(?:[0-9]+|\{[A-Za-z_][A-Za-z0-9_]*\})$/;
const PARAMETER_NAME_START = /[A-Za-z_]/;
const PARAMETER_NAME_REST = /[A-Za-z0-9_]/;
const SPECIAL_PARAMETER = /[0-9@*#?$!-]/;
const DOUBLE_QUOTE_ESCAPABLE = new Set(["$", "`", '"', "\\"]);

const ANSI_C_SIMPLE_ESCAPES: Readonly<Record<string, string>> = {
  a: "\x07",
  b: "\b",
  e: "\x1b",
  E: "\x1b",
  f: "\f",
  n: "\n",
  r: "\r",
  t: "\t",
  v: "\v",
  "\\": "\\",
  "'": "'",
  '"': '"',
  "?": "?",
};

const ANSI_C_NUMERIC_ESCAPES: ReadonlyArray<[string, RegExp, number]> = [
  ["x", /^[0-9A-Fa-f]{1,2}/, 16],
  ["u", /^[0-9A-Fa-f]{1,4}/, 16],
  ["U", /^[0-9A-Fa-f]{1,8}/, 16],
];

class UnterminatedConstruct extends Error {}

interface ExpansionFindings {
  kinds: Set<ShellExpansion>;
  parameters: Set<string>;
  substitutions: ShellToken[][];
}

function newFindings(): ExpansionFindings {
  return { kinds: new Set(), parameters: new Set(), substitutions: [] };
}

interface PendingHeredoc {
  delimiter: string;
  delimiterQuoted: boolean;
  stripsTabs: boolean;
}

/** The tokens bash would see, or null for an unclosed quote or substitution. */
export function lexShell(command: string): ShellToken[] | null {
  try {
    return lexList(command, 0, false).tokens;
  } catch (error) {
    if (error instanceof UnterminatedConstruct) {
      return null;
    }
    throw error;
  }
}

function lexList(
  src: string,
  start: number,
  endsAtUnmatchedParen: boolean,
): { tokens: ShellToken[]; end: number } {
  const tokens: ShellToken[] = [];
  const pendingHeredocs: PendingHeredoc[] = [];
  let heredocDelimiterNext: { stripsTabs: boolean } | null = null;
  let openParens = 0;
  let i = start;

  while (i < src.length) {
    const c = src[i];

    if (c === " " || c === "\t") {
      i++;
      continue;
    }
    if (c === "\\" && src[i + 1] === "\n") {
      i += 2;
      continue;
    }
    if (c === "\n") {
      tokens.push({ kind: "operator", op: "\n", start: i, end: i + 1 });
      i = readHeredocBodies(src, i + 1, pendingHeredocs, tokens);
      pendingHeredocs.length = 0;
      continue;
    }
    if (c === "#") {
      const end = lineEnd(src, i);
      tokens.push({
        kind: "comment",
        text: src.slice(i + 1, end),
        start: i,
        end,
      });
      i = end;
      continue;
    }

    const redirect =
      processSubstitutionBody(src, i) === null
        ? matchOperator(src, i, REDIRECT_OPERATORS)
        : null;
    if (redirect) {
      tokens.push({
        kind: "redirect",
        op: redirect.op,
        fd: null,
        start: i,
        end: redirect.end,
      });
      heredocDelimiterNext = heredocOpening(redirect.op);
      i = redirect.end;
      continue;
    }

    const control = matchOperator(src, i, CONTROL_OPERATORS);
    if (control?.op === ")" && endsAtUnmatchedParen && openParens === 0) {
      return { tokens, end: i };
    }
    if (control) {
      if (control.op === "(") openParens++;
      if (control.op === ")" && openParens > 0) openParens--;
      tokens.push({
        kind: "operator",
        op: control.op,
        start: i,
        end: control.end,
      });
      i = control.end;
      continue;
    }

    const word = readWord(src, i);
    i = word.end;

    const isRedirectTarget = tokens.at(-1)?.kind === "redirect";
    const fdRedirect = isRedirectTarget
      ? null
      : redirectWithFdPrefix(src, word);
    if (fdRedirect) {
      tokens.push(fdRedirect);
      heredocDelimiterNext = heredocOpening(fdRedirect.op);
      i = fdRedirect.end;
      continue;
    }

    tokens.push(word);
    if (heredocDelimiterNext) {
      pendingHeredocs.push({
        delimiter: word.text,
        delimiterQuoted: word.quoted,
        stripsTabs: heredocDelimiterNext.stripsTabs,
      });
      heredocDelimiterNext = null;
    }
  }

  if (endsAtUnmatchedParen) {
    throw new UnterminatedConstruct();
  }
  return { tokens, end: i };
}

function heredocOpening(
  op: ShellRedirectOperator,
): { stripsTabs: boolean } | null {
  if (op === "<<") return { stripsTabs: false };
  if (op === "<<-") return { stripsTabs: true };
  return null;
}

function redirectWithFdPrefix(
  src: string,
  word: ShellWord,
): ShellRedirect | null {
  const operatorStart = skipContinuations(src, word.end);
  const next = src[operatorStart];
  const redirectFollows =
    (next === "<" || next === ">") &&
    processSubstitutionBody(src, operatorStart) === null;
  const isFdPrefix =
    !word.quoted &&
    word.expansions.length === 0 &&
    REDIRECT_FD_PREFIX.test(word.text);
  if (!redirectFollows || !isFdPrefix) {
    return null;
  }
  const redirect = matchOperator(src, operatorStart, REDIRECT_OPERATORS);
  if (!redirect) {
    return null;
  }
  return {
    kind: "redirect",
    op: redirect.op,
    fd: word.text,
    start: word.start,
    end: redirect.end,
  };
}

/** Where `i` lands once bash has removed any `\`-newline pairs starting there. */
function skipContinuations(src: string, i: number): number {
  let j = i;
  while (src.startsWith("\\\n", j)) j += 2;
  return j;
}

/** The longest operator at `i`, read across line continuations as bash does. */
function matchOperator<T extends string>(
  src: string,
  i: number,
  operators: readonly T[],
): { op: T; end: number } | null {
  for (const op of operators) {
    let j = i;
    let matched = 0;
    while (matched < op.length) {
      if (matched > 0) j = skipContinuations(src, j);
      if (src[j] !== op[matched]) break;
      j++;
      matched++;
    }
    if (matched === op.length) {
      return { op, end: j };
    }
  }
  return null;
}

/** Index just past the `(` of a `<(` or `>(` at `i`, or null if none opens. */
function processSubstitutionBody(src: string, i: number): number | null {
  if (src[i] !== "<" && src[i] !== ">") return null;
  const paren = skipContinuations(src, i + 1);
  return src[paren] === "(" ? paren + 1 : null;
}

function breaksUnquotedWord(src: string, i: number): boolean {
  return (
    UNQUOTED_WORD_BREAKS.has(src[i]) && processSubstitutionBody(src, i) === null
  );
}

function lineEnd(src: string, from: number): number {
  const newline = src.indexOf("\n", from);
  return newline === -1 ? src.length : newline;
}

function readHeredocBodies(
  src: string,
  from: number,
  pending: readonly PendingHeredoc[],
  tokens: ShellToken[],
): number {
  let i = from;
  for (const heredoc of pending) {
    const bodyStart = i;
    for (;;) {
      const end = lineEnd(src, i);
      const line = src.slice(i, end);
      const candidate = heredoc.stripsTabs ? line.replace(/^\t+/, "") : line;
      const reachedDelimiter = candidate === heredoc.delimiter;
      // bash runs an unterminated heredoc anyway, with the body up to EOF.
      if (reachedDelimiter || end === src.length) {
        const bodyEnd = reachedDelimiter ? i : end;
        const found = heredoc.delimiterQuoted
          ? newFindings()
          : heredocExpansions(src, bodyStart, bodyEnd);
        tokens.push({
          kind: "heredoc",
          body: src.slice(bodyStart, bodyEnd),
          expansions: [...found.kinds],
          parameters: [...found.parameters],
          substitutions: found.substitutions,
          start: bodyStart,
          end,
        });
        i = end === src.length ? end : end + 1;
        break;
      }
      i = end + 1;
    }
  }
  return i;
}

function heredocExpansions(
  src: string,
  start: number,
  end: number,
): ExpansionFindings {
  const found = newFindings();
  let i = start;
  while (i < end) {
    const c = src[i];
    if (c === "\\") {
      i += 2;
    } else if (c === "$") {
      i = scanDollar(src, i, found);
    } else if (c === "`") {
      i = scanBackticks(src, i + 1, found);
    } else {
      i++;
    }
  }
  return found;
}

function readWord(src: string, start: number): ShellWord {
  const found = newFindings();
  let text = "";
  // `text` with every quoted, escaped or expanded span reduced to one `x`.
  let unquotedShape = "";
  let quoted = false;
  let i = start;
  // A trailing line continuation joins nothing, so it is not in the span.
  let contentEnd = start;

  for (; i < src.length; contentEnd = i) {
    const c = src[i];

    if (c === "\\" && src[i + 1] === "\n") {
      const afterContinuations = skipContinuations(src, i);
      if (
        afterContinuations >= src.length ||
        breaksUnquotedWord(src, afterContinuations)
      ) {
        break;
      }
      i = afterContinuations;
      continue;
    }
    if (c === "\\") {
      if (i + 1 >= src.length) {
        text += c;
        i++;
      } else {
        text += src[i + 1];
        quoted = true;
        i += 2;
      }
      unquotedShape += "x";
      continue;
    }
    if (c === "'") {
      const close = src.indexOf("'", i + 1);
      if (close === -1) throw new UnterminatedConstruct();
      text += src.slice(i + 1, close);
      unquotedShape += "x";
      quoted = true;
      i = close + 1;
      continue;
    }
    const afterDollar = c === "$" ? skipContinuations(src, i + 1) : i;
    if (c === '"' || (c === "$" && src[afterDollar] === '"')) {
      const scanned = scanDoubleQuoted(src, afterDollar + 1, found);
      text += scanned.text;
      unquotedShape += "x";
      quoted = true;
      i = scanned.end;
      continue;
    }
    if (c === "$" && src[afterDollar] === "'") {
      const scanned = scanAnsiC(src, afterDollar + 1);
      text += scanned.text;
      unquotedShape += "x";
      quoted = true;
      i = scanned.end;
      continue;
    }
    if (c === "$") {
      const end = scanDollar(src, i, found);
      text += src.slice(i, end);
      unquotedShape += "x";
      i = end;
      continue;
    }
    if (c === "`") {
      const end = scanBackticks(src, i + 1, found);
      text += src.slice(i, end);
      unquotedShape += "x";
      i = end;
      continue;
    }
    const processBody = processSubstitutionBody(src, i);
    if (processBody !== null) {
      found.kinds.add("process");
      const end = scanCommandSubstitution(src, processBody, found);
      text += src.slice(i, end);
      unquotedShape += "x";
      i = end;
      continue;
    }
    if (UNQUOTED_WORD_BREAKS.has(c)) {
      break;
    }
    text += c;
    unquotedShape += c;
    i++;
  }

  return {
    kind: "word",
    text,
    quoted,
    expansions: [...found.kinds],
    parameters: [...found.parameters],
    substitutions: found.substitutions,
    braceExpansion: hasBraceGroup(unquotedShape),
    pathnameExpansion: /[*?]|\[.*\]/.test(unquotedShape),
    start,
    end: contentEnd,
  };
}

/** A `{` with a matching `}` and a `,` or `..` between them. */
function hasBraceGroup(unquotedShape: string): boolean {
  let open = unquotedShape.indexOf("{");
  while (open !== -1) {
    let depth = 0;
    let separated = false;
    for (let i = open; i < unquotedShape.length; i++) {
      const c = unquotedShape[i];
      if (c === "{") {
        depth++;
      } else if (c === "}") {
        depth--;
        if (depth === 0) {
          if (separated) return true;
          break;
        }
      } else if (c === "," || unquotedShape.startsWith("..", i)) {
        separated = true;
      }
    }
    open = unquotedShape.indexOf("{", open + 1);
  }
  return false;
}

function scanDoubleQuoted(
  src: string,
  start: number,
  found: ExpansionFindings,
): { text: string; end: number } {
  let text = "";
  let i = start;
  while (i < src.length) {
    const c = src[i];
    if (c === '"') {
      return { text, end: i + 1 };
    }
    if (c === "\\" && src[i + 1] === "\n") {
      i += 2;
    } else if (c === "\\" && DOUBLE_QUOTE_ESCAPABLE.has(src[i + 1])) {
      text += src[i + 1];
      i += 2;
    } else if (c === "$") {
      const end = scanDollar(src, i, found);
      text += src.slice(i, end);
      i = end;
    } else if (c === "`") {
      const end = scanBackticks(src, i + 1, found);
      text += src.slice(i, end);
      i = end;
    } else {
      text += c;
      i++;
    }
  }
  throw new UnterminatedConstruct();
}

/** End of the expansion at `start`, or `start + 1` for a literal `$`. */
function scanDollar(
  src: string,
  start: number,
  found: ExpansionFindings,
): number {
  const nextAt = skipContinuations(src, start + 1);
  const next = src[nextAt];
  const secondParenAt = skipContinuations(src, nextAt + 1);
  if (next === "(" && src[secondParenAt] === "(") {
    const arithmeticEnd = scanArithmetic(src, secondParenAt + 1, found);
    if (arithmeticEnd !== null) {
      found.kinds.add("arithmetic");
      return arithmeticEnd;
    }
  }
  if (next === "(") {
    found.kinds.add("command");
    return scanCommandSubstitution(src, nextAt + 1, found);
  }
  if (next === "{") {
    found.kinds.add("parameter");
    const name = bracedParameterName(src, nextAt + 1);
    if (name !== null) found.parameters.add(name);
    return scanBracedParameter(src, nextAt + 1, found);
  }
  if (next === "[") {
    found.kinds.add("arithmetic");
    return scanLegacyArithmetic(src, nextAt + 1, found);
  }
  if (next !== undefined && PARAMETER_NAME_START.test(next)) {
    found.kinds.add("parameter");
    let end = nextAt + 1;
    for (;;) {
      const candidate = skipContinuations(src, end);
      if (!PARAMETER_NAME_REST.test(src[candidate] ?? "")) {
        found.parameters.add(src.slice(nextAt, end).replaceAll("\\\n", ""));
        return end;
      }
      end = candidate + 1;
    }
  }
  if (next !== undefined && SPECIAL_PARAMETER.test(next)) {
    found.kinds.add("parameter");
    found.parameters.add(next);
    return nextAt + 1;
  }
  return start + 1;
}

function scanCommandSubstitution(
  src: string,
  start: number,
  found: ExpansionFindings,
): number {
  const inner = lexList(src, start, true);
  found.substitutions.push(inner.tokens);
  return inner.end + 1;
}

function scanBackticks(
  src: string,
  start: number,
  found: ExpansionFindings,
): number {
  found.kinds.add("command");
  let i = start;
  while (i < src.length) {
    if (src[i] === "\\") {
      i += 2;
    } else if (src[i] === "`") {
      found.substitutions.push(lexBacktickBody(src, start, i));
      return i + 1;
    } else {
      i++;
    }
  }
  throw new UnterminatedConstruct();
}

/** Lexes the body raw: its `\``, `\$` and `\\` read as escapes either way. */
function lexBacktickBody(
  src: string,
  start: number,
  end: number,
): ShellToken[] {
  const tokens = lexList(src.slice(start, end), 0, false).tokens;
  return tokens.map((token) => shiftToken(token, start));
}

function shiftToken(token: ShellToken, offset: number): ShellToken {
  const shifted = {
    ...token,
    start: token.start + offset,
    end: token.end + offset,
  };
  if (shifted.kind === "word" || shifted.kind === "heredoc") {
    shifted.substitutions = shifted.substitutions.map((inner) =>
      inner.map((t) => shiftToken(t, offset)),
    );
  }
  return shifted;
}

/** Returns null where bash would reparse `$((` as a nested `$( (…) )`. */
function scanArithmetic(
  src: string,
  start: number,
  found: ExpansionFindings,
): number | null {
  let depth = 0;
  let i = start;
  while (i < src.length) {
    const c = src[i];
    if (c === "(") {
      depth++;
      i++;
    } else if (c === ")" && depth === 0) {
      return src[i + 1] === ")" ? i + 2 : null;
    } else if (c === ")") {
      depth--;
      i++;
    } else {
      i = scanNestedCharacter(src, i, found);
    }
  }
  throw new UnterminatedConstruct();
}

function scanLegacyArithmetic(
  src: string,
  start: number,
  found: ExpansionFindings,
): number {
  let depth = 0;
  let i = start;
  while (i < src.length) {
    const c = src[i];
    if (c === "[") {
      depth++;
      i++;
    } else if (c === "]" && depth === 0) {
      return i + 1;
    } else if (c === "]") {
      depth--;
      i++;
    } else {
      i = scanNestedCharacter(src, i, found);
    }
  }
  throw new UnterminatedConstruct();
}

/** `?` in `${?:-0}` and `${#?}`, `#` in `${#}`, `x` in `${!x}`; null for `${}`. */
function bracedParameterName(src: string, start: number): string | null {
  let i = start;
  const operand = src[i + 1] ?? "";
  if (
    (src[i] === "#" || src[i] === "!") &&
    operand !== "}" &&
    (PARAMETER_NAME_START.test(operand) || SPECIAL_PARAMETER.test(operand))
  ) {
    i++;
  }
  const first = src[i] ?? "";
  if (PARAMETER_NAME_START.test(first)) {
    return src.slice(i).match(/^[A-Za-z_][A-Za-z0-9_]*/)?.[0] ?? null;
  }
  if (/[0-9]/.test(first)) return src.slice(i).match(/^[0-9]+/)?.[0] ?? null;
  return SPECIAL_PARAMETER.test(first) ? first : null;
}

function scanBracedParameter(
  src: string,
  start: number,
  found: ExpansionFindings,
): number {
  let i = start;
  while (i < src.length) {
    if (src[i] === "}") {
      return i + 1;
    }
    i = scanNestedCharacter(src, i, found);
  }
  throw new UnterminatedConstruct();
}

/** Steps over one character, quote or expansion inside `${…}`/`$((…))`. */
function scanNestedCharacter(
  src: string,
  i: number,
  found: ExpansionFindings,
): number {
  const c = src[i];
  if (c === "\\") {
    return i + 2;
  }
  if (c === "'") {
    const close = src.indexOf("'", i + 1);
    if (close === -1) throw new UnterminatedConstruct();
    return close + 1;
  }
  if (c === '"') {
    return scanDoubleQuoted(src, i + 1, found).end;
  }
  if (c === "$") {
    return scanDollar(src, i, found);
  }
  if (c === "`") {
    return scanBackticks(src, i + 1, found);
  }
  return i + 1;
}

function scanAnsiC(src: string, start: number): { text: string; end: number } {
  let text = "";
  // bash drops the rest of a `$'…'` string after a `\0` escape.
  let truncated = false;
  let i = start;
  while (i < src.length) {
    const c = src[i];
    if (c === "'") {
      return { text, end: i + 1 };
    }
    let decoded = c;
    let width = 1;
    if (c === "\\" && i + 1 < src.length) {
      [decoded, width] = decodeAnsiCEscape(src, i + 1);
      width += 1;
    }
    if (decoded === "\0") truncated = true;
    if (!truncated) text += decoded;
    i += width;
  }
  throw new UnterminatedConstruct();
}

/** An escape's character, and its source length after the backslash. */
function decodeAnsiCEscape(src: string, at: number): [string, number] {
  const letter = src[at];
  const simple = ANSI_C_SIMPLE_ESCAPES[letter];
  if (simple !== undefined) {
    return [simple, 1];
  }
  const octal = /^[0-7]{1,3}/.exec(src.slice(at, at + 3));
  if (octal) {
    return [String.fromCharCode(parseInt(octal[0], 8) & 0xff), octal[0].length];
  }
  for (const [prefix, digits, radix] of ANSI_C_NUMERIC_ESCAPES) {
    if (letter !== prefix) continue;
    const match = digits.exec(src.slice(at + 1, at + 9));
    if (!match) break;
    const codePoint = parseInt(match[0], radix);
    const character =
      codePoint <= 0x10ffff
        ? String.fromCodePoint(codePoint)
        : `\\${letter}${match[0]}`;
    return [character, 1 + match[0].length];
  }
  if (letter === "c" && at + 1 < src.length) {
    return [String.fromCharCode(src.charCodeAt(at + 1) & 0x1f), 2];
  }
  return [`\\${letter}`, 1];
}


interface ShellHookPayload {
  hook_event_name?: string;
  command?: string;
  tool_input?: { command?: string };
  workspace_roots?: string[];
}

const LIMITED_COMMANDS: readonly string[] = ["git diff","git log","git show","git grep","git branch","git fetch","git reflog","git worktree add","git worktree remove","node","rg","perl","awk","find","mkdir","sort","uniq"];

const CURSOR_SHELL_EVENT = "beforeShellExecution";
const CURSOR_PRE_TOOL_EVENT = "preToolUse";
const HOME_COPY_FLAG = "--home";
const BUNDLE_IN_WORKSPACE = ".claude/hooks/dist/run.mjs";

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Anywhere in the command, as whole words: over-asking is fine while the harness is broken. */
function firstLimitedCommand(command: string): string | undefined {
  return LIMITED_COMMANDS.find((limited) => {
    const words = limited.split(" ").map(escapeRegExp).join("\\s+");
    return new RegExp(`\\b${words}\\b`).test(command);
  });
}

type RedirectRisk = "write" | "unreadable";

const FILE_WRITE_REDIRECTS: ReadonlySet<string> = new Set([">", ">>", ">|", "&>", "&>>", "<>"]);
const DESCRIPTOR_TARGET = /^(\d+|-)$/;

/** A redirect bash would apply to a file, at any depth of substitution. */
function writesThroughRedirect(tokens: readonly ShellToken[]): boolean {
  return tokens.some((token, index) => {
    if (token.kind === "word" || token.kind === "heredoc") {
      return token.substitutions.some(writesThroughRedirect);
    }
    if (token.kind !== "redirect") {
      return false;
    }
    const next = tokens[index + 1];
    const target = next?.kind === "word" ? next.text : "";
    if (token.op === ">&") {
      return !DESCRIPTOR_TARGET.test(target);
    }
    return FILE_WRITE_REDIRECTS.has(token.op) && target !== "/dev/null";
  });
}

function redirectRisk(command: string): RedirectRisk | undefined {
  const tokens = lexShell(command);
  if (tokens === null) {
    return "unreadable";
  }
  return writesThroughRedirect(tokens) ? "write" : undefined;
}

/** Only in Cursor's payload; the home copy's cwd there is unmeasured. */
function everyWorkspaceRootHasBundle(roots: readonly string[] | undefined): boolean {
  return !!roots?.length && roots.every((root) => existsSync(join(root, BUNDLE_IN_WORKSPACE)));
}

function approvalRequest(limited: string): string {
  return `\`${limited}\` is allowed only within limits the agent-harness guard enforces, and the guard is not running here, so it needs your approval.`;
}

const REDIRECT_APPROVAL_REQUEST: Record<RedirectRisk, string> = {
  write:
    "This command writes through a redirect, which the agent-harness guard confines to the workspace, and the guard is not running here, so it needs your approval.",
  unreadable:
    "This command has an unclosed quote or substitution, so the agent-harness fallback cannot read it for a redirect, and the guard is not running here, so it needs your approval.",
};

function main(): void {
  let payload: ShellHookPayload;
  try {
    payload = JSON.parse(readFileSync(0, "utf8") || "{}") as ShellHookPayload;
  } catch {
    return;
  }
  const event = payload.hook_event_name;
  // Cursor drops an ask on preToolUse, and in Auto-Review on escalated or pre-approved shell calls.
  if (event === CURSOR_PRE_TOOL_EVENT) {
    process.stdout.write("{}");
    return;
  }
  if (
    process.argv.includes(HOME_COPY_FLAG) &&
    everyWorkspaceRootHasBundle(payload.workspace_roots)
  ) {
    return;
  }
  const command = payload.tool_input?.command ?? payload.command ?? "";
  const limited = firstLimitedCommand(command);
  const risk = redirectRisk(command);
  let reason: string;
  if (limited !== undefined) {
    reason = approvalRequest(limited);
  } else if (risk !== undefined) {
    reason = REDIRECT_APPROVAL_REQUEST[risk];
  } else {
    return;
  }
  const verdict =
    event === CURSOR_SHELL_EVENT
      ? { permission: "ask", user_message: reason }
      : {
          hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "ask",
            permissionDecisionReason: reason,
          },
        };
  process.stdout.write(JSON.stringify(verdict));
}

main();
